/**
 * Generates icon union type for all Material Design icons.
 *
 * The idea is to improve DX by allowing devs to use auto complete
 * and search by icon name.
 *
 * In order to regenerate the icon types, just run
 * ```
 * npx ts-node generate-icon-union.ts
 * ```
 */

console.warn('DO NOT IMPORT THIS, USE IT WITH ts-node.')

import { readFileSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'

const vectorIconsDirectory = dirname(dirname(require.resolve('react-native-vector-icons')))

const glyphmap = JSON.parse(readFileSync(join(vectorIconsDirectory, 'glyphmaps/MaterialIcons.json')).toString())

const union = Object.keys(glyphmap)
  .map((name) => `'${name}'`)
  .join('\n  | ')

writeFileSync(
  './material.union-types.ts',
  `/* GENERATED BY generate-icon-union.ts */
export type MaterialIconType =
  | ${union}
`
)
